FROM mcr.microsoft.com/devcontainers/python:3.12-bookworm

RUN curl -L https://github.com/resim-ai/api-client/releases/latest/download/resim-linux-amd64 -o /usr/local/bin/resim \
    && chmod +x /usr/local/bin/resim
